### ISSUE TITLE
Missing eventtype GitHub::Release

### ISSUE THREAD

**Issue by KoenPhilipsenA** [splunk/github_app_for_splunk#23]
The dashboard value_stream_analytics.xml refers to an eventtype GitHub::Release.
But this eventtype is missing from the eventtypes.conf

**Comment by derkkila-splunk** [comment]
Thanks for pointing that out. I've updated the eventtypes.conf file and the next release will have this update. In the meantime, you can create your own eventtype and provide this as the search:
`github_webhooks` action IN ("released","published") release.id=*
