### ISSUE TITLE
Mean Time To Remediation Dashboard

### ISSUE THREAD

**Issue by leftrightleft** [splunk/github_app_for_splunk#27]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.  New dashboard request.

**Describe the solution you'd like**
The current Code Scanning dashboard shows the "time to remediation" column for fixed alerts.  It would be nice to have a dashboard that tracks the overall MTTR for Code Scanning alerts.

There are a few requirements:
- Sort and filter by repo, org, and code scanning tool
- Show a trend of the MTTR over time

**Comment by derkkila-splunk** [comment]
Would it be limited to Code Scanning or all Advanced Security alerts? A single place to judge the remediation of all alerts dependency, code scanning, and secrets in one place?

**Comment by leftrightleft** [comment]
Closed with #42
