### ISSUE TITLE
Workflow Analytics Tab: Should it be `queueTime` instead of `queTime`

### ISSUE THREAD

**Issue by rajbos** [splunk/github_app_for_splunk#28]
**Describe the bug**
Workflow Analytics Tab: Should it be `queueTime` instead of `queTime` in the overview pane? Not native English speaker, but it stood out to me.

**To Reproduce**
1. Go to the workflow analytics and see the naming there :-D

**Expected behavior**
Change the naming if that should be the correct text

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Additional context**
I think the definition file is here: https://github.com/splunk/github_app_for_splunk/blob/main/github_app_for_splunk/default/data/ui/views/workflow_analytics.xml

If it helps and someone thinks we should change the 'field' title, I can create a PR for it?

**Comment by leftrightleft** [comment]
I think this change makes sense. Good catch, @rajbos!  @derkkila-splunk you got any thoughts on this change?
