### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by indreshgithub1** [splunk/github_app_for_splunk#43]
**Describe the bug**

05-13-2022 16:57:00.263 -0400 ERROR ExecProcessor - message from "/splunk/bin/python3.7 /splunk/etc/apps/github-audit-log-monitoring-add-on-for-splunk/bin/ghe_audit_log_monitoring.py" RuntimeError: Could not fetch audit log data. Please check your configuration, access token scope / correctness and API rate limits. status_code: 404 - url: https://github.com/api/graphql/enterprises/enterprise-name/audit-log?phrase=&include=all&after=&before=&order=asc&per_page=100 - Response: Not Found

05-13-2022 16:57:00.263 -0400 ERROR ExecProcessor - message from "/splunk/bin/python3.7 /splunk/etc/apps/github-audit-log-monitoring-add-on-for-splunk/bin/ghe_audit_log_monitoring.py"     response.status_code, response.url, response.text
**To Reproduce**

. Go to '...'source = [/splunk/var/log/splunk/splunkd.log]

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/104789144/168389284-8ed8820a-d679-4653-8090-3868200b9092.png)
![image](https://user-images.githubusercontent.com/104789144/168389358-61e6ed9a-138d-4ebd-8106-061fdc4d6871.png)

**Desktop (please complete the following information):**
 
**Additional context**

**Comment by leftrightleft** [comment]
Hey @indreshgithub1 have you configured the audit log by following the directions [here](docs/ghe_audit_logs.MD)?

It seems like it's not pointing at your enterprise name.

**Comment by indreshgithub1** [comment]
@leftrightleft . 

Yes. It was the case. Thanks for your reply.

The host name and enterprise name was incorrect. I have fixed the issue and now its working.

Regards,
Indresh
