### ISSUE TITLE
Dashboard is empty but events are being ingested

### ISSUE THREAD

**Issue by Jasmine-8i8** [splunk/github_app_for_splunk#56]
I can see all Github data is being ingested successfully, but the dashboards all show 0 or 'no data', any idea what is wrong here?

**Comment by israelbgf** [comment]
Same problem here, do we need to do some manual changes on the queries?

**Comment by derkkila-splunk** [comment]
No, no changes to queries, but did you update the macro to include your indexes?

**Comment by derkkila-splunk** [comment]
You can see the required macro changes in the documentation: https://github.com/splunk/github_app_for_splunk#readme

If that doesn't help please comment here!

**Comment by Jasmine-8i8** [comment]
Hi Doug, I definitely looked in the documentation but it is not specific about which macros to change or how to change them. For example if I see all my github data coming in under the index 'github' how would I then change these macros?

**Comment by israelbgf** [comment]
Indeed, noob mistake. You have to search your macros, and edit it with the name of your index (in your case @Jasmine-8i8  `github`). That makes it work.

**Comment by Jasmine-8i8** [comment]
Ah ok I didn't realize we must change the index of every macro.  Thanks both

**Comment by shakerg** [comment]
I'm getting the same issue, going though the build a few times.. I can manually search the data and it's coming in from GHES, but the dashboard has none of the data. I have verified the macro index as well as the connections, everything looks good and as per documentation. 

GHES = 3.6
Splunk Enterprise = 9.0.1
Apps:
  Splunk Add-on for Github 2.0.0 
  GitHub Audit Log Monitoring Add-On for Splunk 1.1.1
  GitHub App for Splunk 1.2.3

<img width="1342" alt="HTTP_Event_Collector___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123311-a26b1cb3-977a-4b14-bd56-943a885bc00d.png">

<img width="1337" alt="Settings___Splunk" src="https://user-images.githubusercontent.com/24681097/192123315-763c7978-e33b-41e4-b574-b07ddd11caf3.png">

<img width="1328" alt="Search___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123318-ad898e71-fc8a-4c53-bc65-cb0af7615b4e.png">

<img width="1149" alt="Code_Scanning_Alerts___Splunk_9_0_1_and_shaker_—_root_splunk___opt_splunk_etc_apps_Splunk_TA_github_local_—_ssh_splunk_—_116×32" src="https://user-images.githubusercontent.com/24681097/192123347-4bb9d286-8832-496d-abe7-08860c180072.png">

<img width="1183" alt="Audit_Log_Activity___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123350-14796e41-aa41-4a83-8e2e-b4a4d78c5abd.png">

**Comment by leftrightleft** [comment]
Just to close out the loop here, @shakerg and I talked offline and got this issue resolved.  Seems like there were issues convincing GitHub to send webhooks to his Splunk instance :)

**Comment by derkkila-splunk** [comment]
Thanks for the update @leftrightleft ! I'll sync up offline to see if I need to update any documentation to help in the future.

**Comment by shakerg** [comment]
After a rebuild, I'm still running into the same issue where I see data coming in but it's not being represented in the dashboard. @leftrightleft and I are going to have another look later this week, if anything comes out of that which I can provide more details around, happy to share those.

**Comment by shakerg** [comment]
*There's a bug in GHES 3.6.0 that affects these webhooks, users should upgrade to 3.6.1+ and then Spunk integration will work as expected.
