### ISSUE TITLE
Dashboard is empty but data is being ingested

### ISSUE THREAD

**Issue by shakerg** [splunk/github_app_for_splunk#58]
Same as Issue #56

I'm getting the same issue, going though the build a few times.. I can manually search the data and it's coming in from GHES, but the dashboard has none of the data. I have verified the macro index as well as the connections, everything looks good and as per documentation. 

GHES = 3.6
Splunk Enterprise = 9.0.1
Apps:
  Splunk Add-on for Github 2.0.0 
  GitHub Audit Log Monitoring Add-On for Splunk 1.1.1
  GitHub App for Splunk 1.2.3

<img width="1342" alt="HTTP_Event_Collector___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123311-a26b1cb3-977a-4b14-bd56-943a885bc00d.png">

<img width="1337" alt="Settings___Splunk" src="https://user-images.githubusercontent.com/24681097/192123315-763c7978-e33b-41e4-b574-b07ddd11caf3.png">

<img width="1328" alt="Search___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123318-ad898e71-fc8a-4c53-bc65-cb0af7615b4e.png">

<img width="1149" alt="Code_Scanning_Alerts___Splunk_9_0_1_and_shaker_—_root_splunk___opt_splunk_etc_apps_Splunk_TA_github_local_—_ssh_splunk_—_116×32" src="https://user-images.githubusercontent.com/24681097/192123347-4bb9d286-8832-496d-abe7-08860c180072.png">

<img width="1183" alt="Audit_Log_Activity___Splunk_9_0_1" src="https://user-images.githubusercontent.com/24681097/192123350-14796e41-aa41-4a83-8e2e-b4a4d78c5abd.png">

_Originally posted by @shakerg in https://github.com/splunk/github_app_for_splunk/issues/56#issuecomment-1257090890_

**Comment by shakerg** [comment]
adding search results
<img width="813" alt="Search___Splunk_9_0_1_and_shaker_—_shaker_splunk____—_-bash_—_116×32" src="https://user-images.githubusercontent.com/24681097/192124289-ae3101eb-9dc5-4daf-8de6-364fa183099c.png">

**Comment by leftrightleft** [comment]
Hey @shakerg mind grabbing a screen cap of the results of this search: 
```
`github_webhooks` | chart count by eventtype
```

**Comment by shakerg** [comment]
piping `chart count by event type` returns zero results

**Comment by shakerg** [comment]
Looks like it works, I think it's safe to note that webhooks won't pull historic values but only new ones post install. Although some of the configuration details lined up... it started working at some point.

**Comment by shakerg** [comment]
There's a bug in GHES 3.6.0 that affects these webhooks, users should upgrade to 3.6.1+ and then Spunk integration will work as expected.
